Add connect-ssh

diff --git a/alias b/alias
--- a/alias
+++ b/alias
@@ -49,7 +49,7 @@ authorize-my-ip =
     ip=$(dig +short myip.opendns.com @resolver1.opendns.com)
     aws ec2 authorize-security-group-ingress --group-id ${1} --cidr $ip/32 --protocol tcp --port 22
   }; f
-
+  
 get-group-id = 
   !f() {
     aws ec2 describe-security-groups --filters Name=group-name,Values=${1} --query SecurityGroups[0].GroupId --output text
@@ -75,3 +75,25 @@ public-ports = ec2 describe-security-groups \
 
 # List or set your region
 region = !f() { [[ $# -eq 1 ]] && aws configure set region "$1" || aws configure get region; }; f
+
+connect-ssh =
+  !f() {
+    instance_output=$(aws ec2 describe-instances \
+                        --instance-ids "${1}" \
+                        --query Reservations[0].Instances[0])
+    ssh_key_file=$(jp -u KeyName <<< "$instance_output")".pem"
+    public_ip=$(jp -u PublicIpAddress <<< "$instance_output")
+    if ! [ -f "$ssh_key_file" ];
+    then
+      echo "Error: Could not locate SSH key: "$ssh_key_file" in current" \
+           "working direcory"
+      exit 1
+    fi
+    if [ "$public_ip" == "null" ];
+    then
+      echo "EC2 Instance: "${1}" does not have a public IP address." \
+           "Unable to connect with SSH."
+      exit 1
+    fi
+    ssh -i "$ssh_key_file" ec2-user@"$public_ip"
+  }; f
